"""
Contrastive prompt pairs for extracting concept directions.
Each concept is defined by (positive_prompts, negative_prompts) pairs.
The direction is estimated as mean(positive_activations) - mean(negative_activations).
"""

# Category 1: Hierarchical concepts (expect: compose well)
HIERARCHICAL_CONCEPTS = {
    "mammal_vs_bird": {
        "positive": [  # mammal
            "The dog ran across the field",
            "A cat sat on the windowsill",
            "The horse galloped through the meadow",
            "Bears hibernate during winter months",
            "The whale surfaced for air",
            "Elephants have excellent memories",
            "The lion prowled through the savanna",
            "Rabbits hopped across the garden",
            "The dolphin leaped out of the water",
            "Wolves hunt in coordinated packs",
            "The bat flew through the cave",
            "Deer grazed peacefully in the forest",
            "The monkey swung between the branches",
            "Tigers are solitary hunters by nature",
            "The fox crept silently through the brush",
            "Cows produce milk for their calves",
            "The seal basked on the rocky shore",
            "Squirrels gathered nuts for the winter",
            "The pig rolled in the cool mud",
            "Rats can squeeze through tiny openings",
        ],
        "negative": [  # bird
            "The eagle soared above the mountains",
            "A robin sat on the garden fence",
            "The penguin waddled across the ice",
            "Owls hunt silently during the night",
            "The parrot mimicked human speech clearly",
            "Flamingos stand gracefully on one leg",
            "The hawk dove toward its prey below",
            "Sparrows chirped loudly every morning early",
            "The crow solved the puzzle quickly",
            "Hummingbirds hover by beating their wings",
            "The swan glided across the still lake",
            "Woodpeckers drummed rhythmically on the tree",
            "The falcon reached incredible diving speeds",
            "Pigeons gathered around the park bench seats",
            "The ostrich ran faster than most animals",
            "Geese flew south for the cold winter",
            "The toucan displayed its colorful large beak",
            "Pelicans scooped fish from the shallow water",
            "The peacock spread its beautiful tail feathers",
            "Chickens scratched at the ground for food",
        ],
    },
    "fruit_vs_vegetable": {
        "positive": [  # fruit
            "The apple was crisp and sweet today",
            "She peeled the orange for her snack",
            "Bananas are rich in potassium and fiber",
            "The strawberry tasted incredibly sweet and fresh",
            "Grapes are used to make fine wine",
            "The mango had a tropical sweet flavor",
            "Cherries are perfect for making delicious pies",
            "The watermelon was refreshing on a hot day",
            "Peaches are fuzzy on the outside skin",
            "The blueberry is packed with many antioxidants",
            "Pineapples grow in warm tropical climates only",
            "The lemon added a sour tangy flavor",
            "Pears are often eaten when ripe and soft",
            "The raspberry has a delicate tart taste",
            "Plums turn into prunes when dried fully",
            "The fig was sweet and full of seeds",
            "Coconuts provide both milk and solid meat",
            "The kiwi had bright green flesh inside",
            "Pomegranates contain hundreds of tiny red seeds",
            "The avocado was perfectly ripe and creamy",
        ],
        "negative": [  # vegetable
            "The carrot was crunchy and bright orange",
            "She chopped the onion for the hot soup",
            "Broccoli is rich in vitamins and minerals",
            "The potato was baked until golden and crispy",
            "Spinach is packed with iron and nutrients",
            "The tomato was red and perfectly ripe today",
            "Celery is mostly water with some good fiber",
            "The cucumber was cool and very refreshing",
            "Peas are small round and bright green",
            "The corn was sweet and freshly picked today",
            "Lettuce forms the base of most green salads",
            "The bell pepper was crunchy and very colorful",
            "Cauliflower can be used as a rice substitute",
            "The zucchini was grilled to absolute perfection",
            "Asparagus spears are tender when cooked just right",
            "The beet had an earthy and sweet flavor",
            "Cabbage is used to make crunchy coleslaw",
            "The mushroom added umami to the hot dish",
            "Green beans are a classic side dish choice",
            "The radish had a sharp peppery strong bite",
        ],
    },
}

# Category 2: Independent attributes (expect: compose well - orthogonal)
INDEPENDENT_CONCEPTS = {
    "positive_vs_negative_sentiment": {
        "positive": [  # positive sentiment
            "This movie was absolutely wonderful and amazing",
            "I love this beautiful sunny warm day outside",
            "The food was delicious and perfectly seasoned here",
            "What a fantastic performance by the whole team",
            "I am thrilled with the excellent final results",
            "The experience was truly enjoyable and memorable overall",
            "Everything worked out perfectly just as we planned",
            "The view from here is breathtakingly beautiful today",
            "I am so grateful for this amazing opportunity",
            "The concert was incredible and deeply inspiring tonight",
            "This is the best day I have had recently",
            "The garden looks absolutely gorgeous in full bloom",
            "I feel wonderful about our new exciting project",
            "The sunset was spectacular with vivid bright colors",
            "Such a delightful surprise to see you here",
            "The book was captivating from start to the finish",
            "I am overjoyed with how everything turned out",
            "The children were laughing and playing so happily",
            "What a magnificent achievement by the whole group",
            "The weather is perfect for a nice long walk",
        ],
        "negative": [  # negative sentiment
            "This movie was absolutely terrible and very boring",
            "I hate this cold miserable rainy day outside",
            "The food was disgusting and completely inedible here",
            "What a horrible performance by the entire team",
            "I am disappointed with the poor final results",
            "The experience was truly awful and very forgettable",
            "Everything went wrong just as I had feared",
            "The view from here is depressingly ugly today",
            "I am so frustrated by this wasted opportunity",
            "The concert was dreadful and painfully long tonight",
            "This is the worst day I have had recently",
            "The garden looks absolutely terrible and totally dead",
            "I feel miserable about our failing doomed project",
            "The sunset was blocked by thick ugly dark clouds",
            "Such a terrible shock to hear that awful news",
            "The book was boring from start to the finish",
            "I am devastated with how everything turned out",
            "The children were crying and fighting so angrily",
            "What a pathetic failure by the whole entire group",
            "The weather is awful for doing anything at all",
        ],
    },
    "formal_vs_casual": {
        "positive": [  # formal
            "I would like to respectfully submit my proposal",
            "The committee shall convene at the designated time",
            "We hereby acknowledge receipt of your formal correspondence",
            "The investigation has yielded the following key findings",
            "It is imperative that we address this matter promptly",
            "The aforementioned conditions must be met in full",
            "We wish to express our sincere deepest gratitude",
            "The results of the analysis are presented herein",
            "In accordance with established protocol and all guidelines",
            "The organization maintains its commitment to high excellence",
            "Furthermore the data suggests a significant clear trend",
            "We respectfully request your prompt attention to this",
            "The proceedings will be conducted in proper due order",
            "It has come to our immediate attention that this",
            "The proposal merits careful thorough serious consideration overall",
            "We shall endeavor to meet all stated clear objectives",
            "The evidence substantiates the claims made in full",
            "In conclusion the findings support our initial hypothesis",
            "The institution upholds the highest professional ethical standards",
            "We recommend the following course of immediate action",
        ],
        "negative": [  # casual
            "Hey what is up how is it going today",
            "Yeah so basically the thing is pretty cool right",
            "Gonna grab some food want to come along too",
            "Dude that was like totally awesome and so wild",
            "So anyway I was just thinking about random stuff",
            "Lol that is so funny I can not even",
            "Nah I do not really feel like doing that",
            "Okay cool so let us just wing it then",
            "Whatever works for you is fine with me honestly",
            "Man that movie was such a total waste of time",
            "Yep sounds good let us do it right now",
            "Oops my bad I totally forgot about that thing",
            "Alright let us just chill and hang out here",
            "No way that is crazy I had no idea",
            "Sup everyone ready to get this party going or what",
            "Haha yeah that is pretty much what happened yesterday",
            "Ugh I really do not want to deal with that",
            "Sweet that is exactly what I was hoping for",
            "Yo check this out it is really pretty neat",
            "Meh it was okay nothing too special or exciting",
        ],
    },
}

# Category 3: Semantic relations (expect: partial composition)
SEMANTIC_CONCEPTS = {
    "big_vs_small": {
        "positive": [  # big
            "The enormous elephant towered over the small trees",
            "A massive building dominated the entire city skyline",
            "The giant wave crashed against the rocky cliffside",
            "Huge crowds gathered in the large open square",
            "The colossal statue stood tall in the wide harbor",
            "An immense forest stretched across the vast landscape",
            "The gigantic whale swam through the deep blue ocean",
            "A tremendous explosion shook the ground for many miles",
            "The vast desert extended to the far distant horizon",
            "An enormous crater marked the ancient impact site here",
            "The towering mountain peak pierced through the thick clouds",
            "A massive glacier slowly carved through the wide valley",
            "The great pyramid rose majestically from the flat desert",
            "An oversized truck blocked the entire narrow road ahead",
            "The sprawling mansion had over fifty rooms and halls",
            "A large boulder blocked the narrow mountain trail ahead",
            "The grand cathedral had incredibly high vaulted ceilings",
            "An expansive lake sparkled under the bright summer sun",
            "The bulky package barely fit through the front door",
            "A wide river flowed through the broad fertile plains",
        ],
        "negative": [  # small
            "The tiny mouse squeezed through the narrow small crack",
            "A miniature house sat on the little shelf edge",
            "The little bird perched on the thin slender branch",
            "Small droplets formed on the cold window glass pane",
            "The compact car fit easily into the tight spot",
            "A minuscule insect crawled across the smooth flat leaf",
            "The petite woman wore a delicate thin gold necklace",
            "A narrow path wound through the dense thick forest",
            "The slim book fit easily into a small pocket",
            "A microscopic organism was visible only under the lens",
            "The modest cottage had just two very small rooms",
            "A short fence surrounded the tiny little garden area",
            "The thin thread was barely visible to the naked eye",
            "A small pebble skipped across the calm still water",
            "The slight breeze barely rustled the light thin leaves",
            "A diminutive figure stood alone in the big empty hall",
            "The fine grain of sand sparkled in the bright light",
            "A wee kitten curled up on the soft warm pillow",
            "The brief note contained only a few simple words",
            "A limited space forced them to think very creatively",
        ],
    },
    "hot_vs_cold": {
        "positive": [  # hot
            "The scorching sun beat down on the dry desert",
            "Boiling water bubbled vigorously in the large steel pot",
            "The blazing fire warmed the entire cold dark room",
            "A sweltering heat wave gripped the whole entire city",
            "The molten lava flowed slowly down the steep mountain",
            "Steaming hot coffee filled the cold morning kitchen air",
            "The tropical sun made everything unbearably hot and humid",
            "A burning sensation spread quickly through the dry throat",
            "The sizzling pan cooked the food to perfection fast",
            "Warm summer nights brought fireflies to the open garden",
            "The heated debate continued well into the late evening",
            "A fiery sunset painted the whole sky bright orange",
            "The toasty cabin provided shelter from the cold storm",
            "Blistering temperatures kept most people safely indoors today",
            "The volcanic springs bubbled with naturally hot clear water",
            "A warm embrace made everything feel better right away",
            "The roasting oven filled the house with great aromas",
            "Sultry weather made the air feel thick and heavy",
            "The thermal vent released superheated water from far below",
            "A feverish child rested under light thin cool sheets",
        ],
        "negative": [  # cold
            "The freezing wind cut through their warm thick coats",
            "Icy roads made driving extremely dangerous this dark morning",
            "The frigid water numbed their hands almost immediately then",
            "A bitter cold front swept across the open plains",
            "The frozen lake glistened under the pale winter moonlight",
            "Chilling temperatures dropped well below zero degrees last night",
            "The glacial pace of change frustrated everyone involved greatly",
            "A frosty morning covered everything in thin white ice",
            "The arctic blast brought record low temperatures this week",
            "Snowflakes drifted gently through the still cold winter air",
            "The cool breeze provided welcome relief from the heat",
            "A wintry landscape stretched out before their tired eyes",
            "The refrigerated room kept the fresh food safely preserved",
            "Hypothermia set in after hours in the cold water",
            "The blizzard brought everything to a complete frozen standstill",
            "A cold shower helped wake him up every single morning",
            "The numb fingers struggled to grip the icy metal bar",
            "Permafrost preserved ancient remains for thousands of long years",
            "The crisp autumn air signaled the end of warm summer",
            "A cold draft seeped through the gap under the door",
        ],
    },
}

# Category 4: Syntactic features (expect: mixed)
SYNTACTIC_CONCEPTS = {
    "past_vs_present": {
        "positive": [  # past tense
            "The dog walked slowly across the muddy wet field",
            "She cooked dinner for the entire large family yesterday",
            "They traveled to Paris last summer for vacation time",
            "He finished the report before the final strict deadline",
            "The team won the championship game last Friday night",
            "She painted a beautiful landscape of the rolling hills",
            "They discussed the proposal at the morning team meeting",
            "He discovered an old map in the dusty dark attic",
            "The children played in the park until evening came",
            "She graduated from the university with top highest honors",
            "They built a new house on the empty vacant lot",
            "He solved the difficult math problem rather quickly then",
            "The cat chased the mouse around the cluttered messy room",
            "She wrote a long letter to her dear old friend",
            "They celebrated the victory with a big festive dinner",
            "He climbed the tall mountain in just three short days",
            "The rain stopped just before the outdoor event started",
            "She organized the files into neat orderly proper folders",
            "They watched the movie together on the comfortable old couch",
            "He fixed the broken fence in the back wide yard",
        ],
        "negative": [  # present tense
            "The dog walks slowly across the muddy wet field now",
            "She cooks dinner for the entire large family tonight",
            "They travel to Paris every summer for vacation time",
            "He finishes the report before the final strict deadline",
            "The team wins the championship game this Friday night",
            "She paints a beautiful landscape of the rolling hills",
            "They discuss the proposal at the morning team meeting",
            "He discovers an old map in the dusty dark attic",
            "The children play in the park until evening comes",
            "She graduates from the university with top highest honors",
            "They build a new house on the empty vacant lot",
            "He solves the difficult math problem rather quickly today",
            "The cat chases the mouse around the cluttered messy room",
            "She writes a long letter to her dear old friend",
            "They celebrate the victory with a big festive dinner",
            "He climbs the tall mountain in just three short days",
            "The rain stops just before the outdoor event starts",
            "She organizes the files into neat orderly proper folders",
            "They watch the movie together on the comfortable old couch",
            "He fixes the broken fence in the back wide yard",
        ],
    },
    "singular_vs_plural": {
        "positive": [  # singular
            "The child runs quickly through the big open park",
            "A bird sings sweetly on the thin tree branch",
            "The student reads quietly in the school library room",
            "A flower blooms brightly in the warm spring garden",
            "The car drives fast down the long empty highway",
            "A worker builds carefully on the new large project",
            "The cat sleeps peacefully on the soft warm cushion",
            "A teacher explains patiently to the young new student",
            "The ship sails smoothly across the calm blue ocean",
            "A scientist studies closely the new rare sample data",
            "The dog barks loudly at the passing mail carrier",
            "A musician plays beautifully at the evening grand concert",
            "The tree grows tall beside the old stone brick wall",
            "A doctor examines thoroughly the patient in the clinic",
            "The book sits neatly on the wooden desk top shelf",
            "A painter creates carefully a new beautiful large canvas",
            "The river flows swiftly through the deep narrow canyon",
            "A chef prepares expertly the special evening dinner dish",
            "The star shines brightly in the dark clear night sky",
            "A horse gallops freely across the wide open green field",
        ],
        "negative": [  # plural
            "The children run quickly through the big open park",
            "Many birds sing sweetly on the thin tree branches",
            "The students read quietly in the school library room",
            "Some flowers bloom brightly in the warm spring garden",
            "The cars drive fast down the long empty highway",
            "Many workers build carefully on the new large project",
            "The cats sleep peacefully on the soft warm cushions",
            "Several teachers explain patiently to the young new students",
            "The ships sail smoothly across the calm blue ocean",
            "Many scientists study closely the new rare sample data",
            "The dogs bark loudly at the passing mail carriers",
            "Several musicians play beautifully at the evening grand concert",
            "The trees grow tall beside the old stone brick wall",
            "Many doctors examine thoroughly the patients in the clinic",
            "The books sit neatly on the wooden desk top shelf",
            "Several painters create carefully new beautiful large canvases",
            "The rivers flow swiftly through the deep narrow canyons",
            "Many chefs prepare expertly the special evening dinner dishes",
            "The stars shine brightly in the dark clear night sky",
            "Several horses gallop freely across the wide open field",
        ],
    },
}

# Category 5: Entangled/competing (expect: fail to compose)
ENTANGLED_CONCEPTS = {
    "happy_vs_sad": {
        "positive": [  # happy
            "She smiled brightly as she heard the great news",
            "The celebration was filled with joy and warm laughter",
            "He felt elated after receiving the wonderful promotion today",
            "The children giggled with pure delight at the surprise",
            "A wave of happiness washed over her weary tired face",
            "The reunion brought tears of joy to all their eyes",
            "He danced with glee when the results came back",
            "The cheerful melody lifted everyone is spirits up high",
            "She beamed with pride at her big accomplishment today",
            "The joyful crowd cheered enthusiastically for the winning team",
            "His heart swelled with contentment and deep inner peace",
            "The laughter echoed through the halls of the building",
            "She felt blessed and grateful for her wonderful loving family",
            "The happy couple embraced warmly after the long trip",
            "A feeling of bliss filled the warm sunny bright room",
            "He grinned from ear to ear with pure delight",
            "The festive atmosphere made everyone feel warm and welcome",
            "She jumped for joy when she got the good news",
            "The world seemed brighter and more beautiful than ever",
            "His optimism was contagious and spread to all around",
        ],
        "negative": [  # sad
            "She wept quietly as she heard the terrible news",
            "The funeral was filled with grief and heavy sorrow",
            "He felt devastated after receiving the awful rejection today",
            "The children cried with deep despair at the bad loss",
            "A wave of sadness washed over her weary tired face",
            "The departure brought tears of sorrow to all their eyes",
            "He slumped with despair when the results came back",
            "The mournful melody brought everyone is spirits way down",
            "She hung her head in shame at her big failure",
            "The somber crowd mourned silently for the tragic sad loss",
            "His heart ached with loneliness and deep inner pain",
            "The sobbing echoed through the halls of the building",
            "She felt isolated and abandoned by her distant cold family",
            "The grieving couple sat in silence after the bad news",
            "A feeling of emptiness filled the dark cold gloomy room",
            "He frowned deeply as misery took hold of his mind",
            "The gloomy atmosphere made everyone feel cold and unwelcome",
            "She collapsed in tears when she got the bad news",
            "The world seemed darker and more hopeless than ever",
            "His pessimism was contagious and spread to all around",
        ],
    },
    "true_vs_false": {
        "positive": [  # true statements
            "The Earth revolves around the Sun every single year",
            "Water freezes at zero degrees Celsius at sea level",
            "Paris is the capital city of France in Europe",
            "Humans need oxygen to breathe and stay alive always",
            "The speed of light is the fastest possible speed",
            "DNA carries the genetic information in all living cells",
            "The Pacific Ocean is the largest ocean on the Earth",
            "Gravity keeps the planets in orbit around our Sun",
            "Plants convert sunlight into energy through photosynthesis always",
            "The Moon causes tides on Earth through gravitational pull",
            "Diamonds are made of carbon atoms arranged in crystal",
            "The human heart has exactly four separate distinct chambers",
            "Mount Everest is the tallest mountain above sea level",
            "Sound travels faster through water than through normal air",
            "The Amazon is the largest river by water volume",
            "Iron is attracted to magnets due to its properties",
            "The Sahara is the largest hot desert in the world",
            "Antibiotics are used to treat harmful bacterial infections only",
            "Lightning is caused by electrical discharge in the atmosphere",
            "The human body has exactly two hundred and six bones",
        ],
        "negative": [  # false statements
            "The Earth revolves around the Moon every single year",
            "Water freezes at fifty degrees Celsius at sea level",
            "Berlin is the capital city of France in Europe",
            "Humans need helium to breathe and stay alive always",
            "The speed of sound is the fastest possible speed",
            "DNA carries the genetic information in only some cells",
            "The Atlantic Ocean is the largest ocean on the Earth",
            "Magnetism keeps the planets in orbit around our Sun",
            "Plants convert moonlight into energy through photosynthesis always",
            "The Sun causes tides on Earth through gravitational pull",
            "Diamonds are made of iron atoms arranged in crystal",
            "The human heart has exactly three separate distinct chambers",
            "Mount Kilimanjaro is the tallest mountain above sea level",
            "Sound travels faster through air than through normal water",
            "The Nile is the largest river by water volume",
            "Iron is attracted to plastic due to its properties",
            "The Gobi is the largest hot desert in the world",
            "Antibiotics are used to treat harmful viral infections only",
            "Lightning is caused by magnetic discharge in the atmosphere",
            "The human body has exactly three hundred and six bones",
        ],
    },
}

ALL_CONCEPTS = {
    "hierarchical": HIERARCHICAL_CONCEPTS,
    "independent": INDEPENDENT_CONCEPTS,
    "semantic": SEMANTIC_CONCEPTS,
    "syntactic": SYNTACTIC_CONCEPTS,
    "entangled": ENTANGLED_CONCEPTS,
}

# For composition tests: pairs of concepts to compose
COMPOSITION_PAIRS = [
    # (category, concept_a, concept_b, expected_composability)
    # Cross-category: independent attributes (should compose well)
    ("independent", "positive_vs_negative_sentiment", "formal_vs_casual", "high"),
    # Within-category hierarchical (should compose)
    ("cross", "mammal_vs_bird", "fruit_vs_vegetable", "high"),
    # Semantic + independent (should compose)
    ("cross", "big_vs_small", "positive_vs_negative_sentiment", "medium"),
    # Semantic + semantic (partial)
    ("cross", "big_vs_small", "hot_vs_cold", "medium"),
    # Syntactic + syntactic (entangled - may fail)
    ("cross", "past_vs_present", "singular_vs_plural", "medium"),
    # Syntactic + semantic (mixed)
    ("cross", "past_vs_present", "big_vs_small", "medium"),
    # Entangled: sentiment + happy/sad (highly correlated - should fail)
    ("cross", "positive_vs_negative_sentiment", "happy_vs_sad", "low"),
    # Entangled: truth + sentiment (may interfere)
    ("cross", "true_vs_false", "positive_vs_negative_sentiment", "low"),
    # Hierarchical + syntactic
    ("cross", "mammal_vs_bird", "singular_vs_plural", "high"),
    # Independent: truth + formal
    ("cross", "true_vs_false", "formal_vs_casual", "medium"),
]
